### ISSUE TITLE
Update the screenshot in README

### ISSUE THREAD

**Issue by mterczynski** [mterczynski/kulki#5]
It depicts an old version of the game

**Comment by ujwalkumar1995** [comment]
Hey @mterczynski 
I can do this. I see that your old game is in polish. Do you want in the game image in polish or in english?

**Comment by mterczynski** [comment]
Hi @ujwalkumar1995 

thanks, I would appreciate that!

You're correct that the old game is in polish. The newest game is in English and has updated graphics (thanks to @dhadley519). Unfortunately, I don't have the newest version deployed on my server but you could run the latest game locally and create a merge request to update the screenshot.
